services:
  - type: web
    name: book-review-api
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
